create table if not exists public.translation_roots (
  id bigint generated by default as identity primary key,
  professional_term text not null unique,
  plain_english_term text not null,
  explanation text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.translation_roots enable row level security;

revoke all on table public.translation_roots from anon, authenticated;
grant select on table public.translation_roots to anon, authenticated;
grant all on table public.translation_roots to service_role;

drop policy if exists "Public can read active translation roots"
on public.translation_roots;

create policy "Public can read active translation roots"
on public.translation_roots
for select
to anon, authenticated
using (active);

insert into public.translation_roots (
  professional_term,
  plain_english_term,
  explanation,
  sort_order
) values
('Director of Photography (DP)','Camera Lead / Head Camera Guy','They are the "Eye" of the film. They choose the cameras, lenses, and how the light hits the actors.',10),
('Gaffer','Head Electrician / Lighting Boss','The person in charge of all the lights and power on set. If the lights go out, it''s their job to fix it.',20),
('Grip','Setup Crew / Rigger','These are the people who build the "bones" of the set—moving heavy gear, setting up stands, and shaping the light.',30),
('Call Sheet','The Daily Schedule','A document sent out every night that tells everyone where to be, what time to start, and what we are filming.',40),
('Location Scout','Place Finder','The person who finds the houses, warehouses, or parks where the movie will be filmed.',50),
('Certificate of Insurance (COI)','Property Protection Paperwork','A standard document that proves the filmmaker is insured. Essential for "Hosts" to feel safe renting out their space.',60),
('Craft Services (Crafty)','Snacks & Drinks','The table on set where everyone goes to get water, coffee, and snacks to keep their energy up.',70),
('Production Assistant (PA)','Entry-Level Help / The Support','The "Swiss Army Knife" of the set. They handle the hard work like moving gear, blocking traffic, and getting coffee.',80),
('Sound Mixer','Audio Recordist','The person wearing headphones who makes sure the actors'' voices are recorded clearly without background noise.',90),
('Boom Operator','Mic Pole Holder','The person who holds the long pole with the microphone over the actors'' heads just out of the camera''s view.',100),
('B-Roll','Extra Footage / Cutaways','Footage that isn''t the main interview or action—like shots of the scenery or close-ups of hands—used to hide edits.',110),
('Script Supervisor','Continuity Watcher','They make sure the actor’s hat is on the same way in every shot so the movie doesn''t look "broken" when edited.',120),
('Prop Master','Item Manager','In charge of everything an actor touches—phones, guns, coffee cups, or tools.',130),
('Production Designer','World Builder','The person who decides what the set looks like—from the color of the walls to the style of the furniture.',140),
('Casting Director','Talent Finder','The person who holds auditions and picks the best actors for each role.',150),
('Line Producer','The Money Manager','The person who runs the budget and makes sure the film doesn''t run out of cash before it''s finished.',160),
('Dailies','Today’s Footage','The raw, unedited footage filmed that day. Usually watched by the Director and Producer at night.',170),
('VFX (Visual Effects)','Digital Magic / Computer Effects','Anything added later with a computer—like explosions, dragons, or changing a green screen to a mountain.',180),
('Foley','Sound Effects Artist','Someone who recreates everyday sounds (footsteps, cloth rustling, door slams) in a studio after filming.',190),
('Colorist','Mood & Look Adjuster','The person who adjusts the colors of the final film to make it look scary, happy, or cinematic.',200)
on conflict (professional_term) do update set
  plain_english_term = excluded.plain_english_term,
  explanation = excluded.explanation,
  sort_order = excluded.sort_order,
  active = true,
  updated_at = now();
